-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(s.SALES_AMOUNT * p.PRICE) as SALES
FROM PRODUCT p
JOIN OFFLINE_SALE s
    ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY  SUM(s.SALES_AMOUNT * p.PRICE) DESC, p.PRODUCT_CODE;