-- 코드를 작성해주세요
SELECT e1.ID, e1.GENOTYPE, e2.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA e1
JOIN ECOLI_DATA e2
ON e1.PARENT_ID = e2.ID
WHERE (e1.GENOTYPE | e2.GENOTYPE) = e1.GENOTYPE
ORDER BY e1.ID ASC;