-- 코드를 작성해주세요
SELECT COUNT(*) as FISH_COUNT
FROM FISH_INFO as INFO
JOIN FISH_NAME_INFO as NAME
    ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE NAME.FISH_NAME LIKE "BASS" OR NAME.FISH_NAME LIKE "SNAPPER";