-- 코드를 입력하세요
SELECT i.INGREDIENT_TYPE, SUM(h.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF as h 
JOIN ICECREAM_INFO as i
    ON i.FLAVOR = h.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY SUM(h.TOTAL_ORDER) ASC;